### ISSUE TITLE
Property has no initializer

### ISSUE THREAD

**Issue by david-wb** [moshegottlieb/ts-json-object#1]
I'm getting this compile time error using the default examples. Any idea how to resolve it?

```
Property 'name' has no initializer and is not definitely assigned in the constructor.  TS2564

    3 | class Book extends JSONObject {
    4 |   @JSONObject.required
  > 5 |   name: string
      |   ^
    6 |   @JSONObject.optional
    7 |   summary?: string
    8 | }
```

**Comment by moshegottlieb** [comment]
Hi David,  
You seem to be compiling with `--strictPropertyInitialization` (or it's set in your `tsconfig.json` file).  
Since we initialize the members dynamically (and throw an error if we can't) - this won't work here.  
Either stop using this option, or add `// @ts-ignore` before the offending lines.  
For example:  
```typescript
class Book extends JSONObject {
    @JSONObject.required
    // @ts-ignore
    name:string
}
```
